### ISSUE TITLE
NuGet Packages not included

### ISSUE THREAD

**Issue by fireydude** [TypecastException/AspNet-Identity-2-With-Integer-Keys#3]
When I open this project in VS2013 SP3 most of the references are not available. This appears to be because you have used NuGet to download the references. How can I fix this problem easily?

**Comment by fireydude** [comment]
Installing the sample as per the blog tutorial seems to do the trick:
PM> Install-Package Microsoft.AspNet.Identity.Samples -Pre

**Comment by xivSolutions** [comment]
You shouldn't even need to do that - VS should pull down all the Nuget packages on first build? Unless I am missing something...

**Comment by fireydude** [comment]
That's what I expected it to do but for some reason it did not work. If it's okay for everyone else then maybe it's just my machine.

**Comment by xivSolutions** [comment]
You may need to allow Nuget Package Restore on your VS.
